/* eslint-disable */


const configDefaults = {
  contractAddress: '',
  erc20: false,
  insight_addr: '',
  insight_tx: '',
  decimals: 0,
  insight_status: true,
  explorer: 'insight',
  disabled: false,
  lib: 'bitgojs',
  type: 'zcash',
  z: false,
  delisted: false,
  segwit: false,
  displayName: '',
  spl: false,
  hasMemo: false,
  web3Node: '',
  web3ChainID: '',
  web3NetworkID: '',
  logo: '',
  txDateSlot: false,
  hasTXHistory: true,
  explorerAddressURL: false,
  addrValidationCheck: '',
};
export const coinConfig = {
  vidulum: {
    ...configDefaults,
    ...{
      name: 'Vidulum',
      logo: 'vidulum.webp',
      insight: 'https://explorer.vidulum.app/',
      insight_tx:
        'https://explorer.vidulum.app/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'VDL',
      z: true,
      dataProviderCode: 'vidulum',
      addrValidationCheck: new RegExp('^v1[a-zA-HJ-NP-Z0-9]{25,39}$'),
    },
  },
  vidulumtoken: {
    ...configDefaults,
    ...{
      disabled: false,
      name: 'Vidulum Token',
      logo: 'newvidulum.png',
      type: 'cosmos',
      lib: 'cosmosjs',
      explorer: 'cosmos',
      cosmosPrefix: 'vdl',
      hasTXHistory: true,
      hasMemo: true,
      txDateSlot: false,
      chainId: 'vidulum-1',
      lcdUrl: 'https://mainnet-lcd.vidulum.app',
      insight: 'https://explorers.vidulum.app/vidulum/',
      explorerAddressURL: 'https://explorers.vidulum.app/',
      insight_addr:
        'https://mainnet-lcd.vidulum.app/cosmos/bank/v1beta1/balances/{SENDER_ADDRESS}',
      symbol: 'VDLtoken',
      denom: 'uvdl',
      dataProviderCode: 'vidulum',
      addrValidationCheck: new RegExp('^vdl[a-zA-HJ-NP-Z0-9]{39}$'),
    },
  },
  nem: {
    ...configDefaults,
    ...{
      name: 'NEM',
      logo: 'nem.webp',
      hasMemo: true,
      decimals: 6,
      type: 'nem',
      lib: 'nemjs',
      explorer: 'nem',
      insight: 'https://explorer.nemtool.com/',
      explorerAddressURL:
        'https://explorer.nemtool.com/#/s_account?account={SENDER_ADDRESS}',
      symbol: 'XEM',
      dataProviderCode: 'nem',
    },
  },
  symbol: {
    ...configDefaults,
    ...{
      name: 'Symbol',
      logo: 'symbol.webp',
      txDateSlot: true,
      hasMemo: true,
      decimals: 6,
      type: 'symbol',
      lib: 'symboljs',
      explorer: 'symbol',
      insight: 'http://explorer.symbolblockchain.io/',
      explorerAddressURL:
        'https://magic.vidulum.app/explorer.symbolblockchain.io/accounts/{SENDER_ADDRESS}',
      nodeEndpoint:
        'https://magic.vidulum.app/ngl-api-301.symbolblockchain.io:3000',
      symbol: 'XYM',
      dataProviderCode: 'symbol',
    },
  },
  dao: {
    ...configDefaults,
    ...{
      name: 'DAO',
      logo: 'dao.webp',
      displayName: 'DAO Maker',
      symbol: 'DAO',
      contractAddress: '0x0f51bb10119727a7e5ea3538074fb341f56b09ad',
      decimals: 18,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'dao-maker',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  ritocoin: {
    ...configDefaults,
    ...{
      name: 'RitoCoin',
      logo: 'ritocoin.webp',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://blockbook.ritocoin.org/',
      insight_addr:
        'https://blockbook.ritocoin.org/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://blockbook.ritocoin.org/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'RITO',
      dataProviderCode: 'rito',
    },
  },
  bitcoinz: {
    ...configDefaults,
    ...{
      name: 'Bitcoinz',
      logo: 'bitcoinz.webp',
      insight: 'https://explorer.btcz.rocks/',
      insight_addr: 'https://explorer.btcz.rocks/api/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://explorer.btcz.rocks/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'BTCZ',
      z: true,
      dataProviderCode: 'bitcoinz',
    },
  },
  bitcoin: {
    ...configDefaults,
    ...{
      name: 'Bitcoin',
      logo: 'bitcoin.webp',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://explorer.bitcoin.com/btc/',
      insight_addr:
        'https://magic.vidulum.app/btc.vidulum.app/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://magic.vidulum.app/btc.vidulum.app/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'BTC',
      dataProviderCode: 'bitcoin',
      addrValidationCheck: new RegExp('^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}$'),
    },
  },
  safe: {
    ...configDefaults,
    ...{
      name: 'SAFE',
      logo: 'newSafecoin.png',
      hasTXHistory: true,
      txDateSlot: true,
      decimals: 18,
      type: 'solana',
      lib: 'solanajs',
      explorer: 'solana',
      insight: 'https://explorer.safecoins.org/',
      symbol: 'SAFE',
      apiEndpoint: 'https://api.mainnet-beta.safecoin.org',
      dataProviderCode: 'safe-coin-2',
    },
  },
  solana: {
    ...configDefaults,
    ...{
      name: 'Solana',
      logo: 'solana.webp',
      txDateSlot: true,
      decimals: 18,
      type: 'solana',
      lib: 'solanajs',
      explorer: 'solana',
      insight: 'https://explorer.solana.com/',
      symbol: 'SOL',
      apiEndpoint: 'https://magic.vidulum.app/api.mainnet-beta.solana.com',
      dataProviderCode: 'solana',
    },
  },
  tron: {
    ...configDefaults,
    ...{
      name: 'Tron',
      logo: 'tron.webp',
      disabled: true,
      decimals: 18,
      hasTXHistory: false,
      type: 'tron',
      lib: 'tronweb',
      explorer: 'tron',
      insight: 'https://etherscan.io/',
      symbol: 'TRON',
      dataProviderCode: 'tron',
    },
  },
  ether1: {
    ...configDefaults,
    ...{
      name: 'ETHO Protocol',
      logo: 'ether1.webp',
      decimals: 18,
      type: 'web3',
      lib: 'web3',
      hasTXHistory: false,
      explorer: 'web3',
      explorerAddressURL:
        'https://blockscout.ethoprotocol.com/address/{SENDER_ADDRESS}',
      insight_addr:
        'https://magic.vidulum.app/blockscout.ethoprotocol.com/api?module=account&action=txlist&address={SENDER_ADDRESS}&page=1&offset=12',
      web3Node: 'https://rpc.ether1.org',
      web3ChainID: '1313114',
      web3NetworkID: '1313114',
      insight: 'https://blockscout.ethoprotocol.com/',
      symbol: 'ETHO',
      dataProviderCode: 'ether-1',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  ethereumclassic: {
    ...configDefaults,
    ...{
      disabled: true,
      name: 'Ethereum Classic',
      logo: 'ethereumclassic.webp',
      decimals: 18,
      type: 'web3',
      lib: 'web3',
      explorer: 'web3',
      insight_addr:
        'https://magic.vidulum.app/blockscout.com/etc/mainnet/api?module=account&action=txlist&address={SENDER_ADDRESS}&page=1&offset=12',
      web3Node: 'https://www.ethercluster.com/etc',
      web3ChainID: '61',
      web3NetworkID: '61',
      insight: 'https://blockscout.com/etc/mainnet/',
      symbol: 'ETC',
      dataProviderCode: 'ethereum-classic',
    },
  },
  ethereum: {
    ...configDefaults,
    ...{
      name: 'Ethereum',
      logo: 'ethereum.webp',
      decimals: 18,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      symbol: 'ETH',
      dataProviderCode: 'ethereum',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  veruscoin: {
    ...configDefaults,
    ...{
      name: 'VerusCoin',
      logo: 'veruscoin.webp',
      insight: 'https://insight.verus.io/',
      insight_addr: 'https://insight.verus.io/api/addr/{SENDER_ADDRESS}',
      insight_tx: 'https://insight.verus.io/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'VRSC',
      z: true,
      dataProviderCode: 'verus-coin',
    },
  },
  dash: {
    ...configDefaults,
    ...{
      name: 'DASH',
      logo: 'dash.webp',
      type: 'bitcoin',
      insight: 'https://explorer.dash.org/insight/',
      insight_addr:
        'https://explorer.dash.org/insight-api/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://explorer.dash.org/insight-api/txs/?address={SENDER_ADDRESS}',
      symbol: 'DASH',
      dataProviderCode: 'dash',
    },
  },
  '5gcash': {
    ...configDefaults,
    ...{
      name: '5gcash',
      logo: '5gcash.webp',
      displayName: '5G-Cash',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://blockbook.fiveg.cash/',
      insight_addr:
        'https://magic.vidulum.app/blockbook.fiveg.cash/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://magic.vidulum.app/blockbook.fiveg.cash/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'VGC',
      z: true,
      dataProviderCode: '5g-cash',
    },
  },
  simplesoftwaresolutions: {
    ...configDefaults,
    ...{
      name: 'Simple Software Solutions',
      logo: 'simplesolutions.png',
      displayName: 'Simple Software Solutions',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://sss.flitswallet.app/',
      insight_addr:
        'https://magic.vidulum.app/sss.flitswallet.app/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://magic.vidulum.app/sss.flitswallet.app/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'SSS',
      z: true,
      dataProviderCode: 'simple-software-solutions',
    },
  },
  litecoinz: {
    ...configDefaults,
    ...{
      name: 'LitecoinZ',
      logo: 'litecoinz.webp',
      insight: 'https://insight.litecoinz.org/',
      insight_addr: 'https://insight.litecoinz.org/api/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://insight.litecoinz.org/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'LTZ',
      z: true,
      dataProviderCode: 'litecoinz',
    },
  },
  snowgem: {
    ...configDefaults,
    ...{
      name: 'Snowgem',
      logo: 'snowgem.webp',
      displayName: 'Tent',
      insight: 'https://explorer.tent.app/',
      insight_addr: 'https://explorer.tent.app/api/addr/{SENDER_ADDRESS}',
      insight_tx: 'https://explorer.tent.app/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'TENT',
      dataProviderCode: 'snowgem',
    },
  },
  '0x': {
    ...configDefaults,
    ...{
      name: '0x',
      logo: '0x.webp',
      symbol: 'ZRX',
      contractAddress: '0xE41d2489571d322189246DaFA5ebDe1F4699F498',
      decimals: 18,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: '0x',
    },
  },
  scriv: {
    ...configDefaults,
    ...{
      name: 'SCRIV',
      logo: 'scriv.webp',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://scriv.zcore.host/',
      insight_addr:
        'https://scriv.zcore.host/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://scriv.zcore.host/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'SCRIV',
      dataProviderCode: 'scriv',
    },
  },
  loopring: {
    ...configDefaults,
    ...{
      name: 'Loopring',
      logo: 'loopring.webp',
      symbol: 'LRC',
      contractAddress: '0xBBbbCA6A901c926F240b89EacB641d8Aec7AEafD',
      decimals: 18,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'loopring',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  digibyte: {
    ...configDefaults,
    ...{
      name: 'DigiByte',
      logo: 'digibyte.webp',
      segwit: true,
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://digibyteblockexplorer.com/',
      insight_addr:
        'https://digibyteblockexplorer.com/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://digibyteblockexplorer.com/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'DGB',
      dataProviderCode: 'digibyte',
    },
  },
  basicattention: {
    ...configDefaults,
    ...{
      name: 'Basic Attention',
      logo: 'basicattention.webp',
      symbol: 'BAT',
      contractAddress: '0x0d8775f648430679a709e98d2b0cb6250d2887ef',
      decimals: 18,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'basic-attention-token',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  ravencoin: {
    ...configDefaults,
    ...{
      name: 'Ravencoin',
      logo: 'ravencoin.webp',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://blockbook.ravencoin.org/',
      insight_addr:
        'https://blockbook.ravencoin.org/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://blockbook.ravencoin.org/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'RVN',
      dataProviderCode: 'ravencoin',
    },
  },
  litecoin: {
    ...configDefaults,
    ...{
      name: 'Litecoin',
      logo: 'litecoin.webp',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://ltcbook.guarda.co/',
      insight_addr:
        'https://ltcbook.guarda.co/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://ltcbook.guarda.co/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'LTC',
      dataProviderCode: 'litecoin',
    },
  },
  zero: {
    ...configDefaults,
    ...{
      name: 'Zero',
      logo: 'zero.webp',
      insight: 'https://insight.zeromachine.io/insight/',
      insight_addr:
        'https://insight.zeromachine.io/insight-api-zero/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://insight.zeromachine.io/insight-api-zero/txs/?address={SENDER_ADDRESS}',
      symbol: 'ZER',
      z: true,
      dataProviderCode: 'zero',
    },
  },
  groestlcoin: {
    ...configDefaults,
    ...{
      name: 'Groestlcoin',
      logo: 'groestlcoin.webp',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://blockbook.groestlcoin.org/',
      insight_addr:
        'https://blockbook.groestlcoin.org/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://blockbook.groestlcoin.org/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'GRS',
      dataProviderCode: 'groestlcoin',
    },
  },
  komodo: {
    ...configDefaults,
    ...{
      name: 'Komodo',
      logo: 'komodo.webp',
      insight: 'https://kmdexplorer.io/',
      insight_addr:
        'https://kmdexplorer.io/insight-api-komodo/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://kmdexplorer.io/insight-api-komodo/txs/?address={SENDER_ADDRESS}',
      symbol: 'KMD',
      z: true,
      dataProviderCode: 'komodo',
    },
  },
  zencash: {
    ...configDefaults,
    ...{
      name: 'Zencash',
      logo: 'zencash.webp',
      displayName: 'Horizen',
      type: 'zencash',
      insight: 'https://explorer.zensystem.io/',
      insight_addr: 'https://explorer.zensystem.io/api/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://explorer.zensystem.io/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'ZEN',
      z: true,
      dataProviderCode: 'zencash',
    },
  },
  zelcash: {
    ...configDefaults,
    ...{
      name: 'Zelcash',
      displayName: 'Flux',
      logo: 'flux.png',
      insight: 'https://explorer.runonflux.io/',
      insight_addr:
        'https://magic.vidulum.app/explorer.runonflux.io/api/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://magic.vidulum.app/explorer.runonflux.io/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'FLUX',
      z: true,
      dataProviderCode: 'zelcash',
    },
  },
  bitcoincash: {
    ...configDefaults,
    ...{
      name: 'Bitcoin Cash',
      logo: 'bitcoincash.webp',
      type: 'bitcoincash',
      explorer: 'bitcoin.com',
      insight: 'https://explorer.bitcoin.com/bch',
      insight_addr:
        'https://rest.bitcoin.com/v2/address/details/{SENDER_ADDRESS}',
      insight_tx:
        'https://rest.bitcoin.com/v2/address/transactions/{SENDER_ADDRESS}',
      symbol: 'BCH',
      dataProviderCode: 'bitcoin-cash',
    },
  },
  zcash: {
    ...configDefaults,
    ...{
      name: 'Zcash',
      logo: 'zcash.webp',
      explorer: 'blockbook',
      insight: 'https://zecblockexplorer.com/',
      insight_addr:
        'https://zecblockexplorer.com/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://zecblockexplorer.com/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'ZEC',
      z: true,
      dataProviderCode: 'zcash',
    },
  },
  zcoin: {
    ...configDefaults,
    ...{
      name: 'Zcoin',
      logo: 'zcoin.webp',
      displayName: 'firo',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://blockbook.zcoin.io/',
      insight_addr:
        'https://magic.vidulum.app/blockbook.zcoin.io/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://magic.vidulum.app/blockbook.zcoin.io/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'FIRO',
      z: true,
      dataProviderCode: 'zcoin',
    },
  },
  ilcoin: {
    ...configDefaults,
    ...{
      name: 'ILCoin',
      logo: 'ilcoin.webp',
      type: 'bitcoin',
      insight: 'https://ilcoinexplorer.com/',
      insight_addr: 'https://ilcoinexplorer.com/api/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://ilcoinexplorer.com/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'ILC',
      dataProviderCode: 'ilcoin',
    },
  },
  bzedge: {
    ...configDefaults,
    ...{
      name: 'BZEdge',
      logo: 'bzedge.webp',
      insight: 'https://explorer.getbze.com/',
      insight_addr:
        'https://explorer.getbze.com/insight-api-bzedge-v2/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://explorer.getbze.com/insight-api-bzedge-v2/txs/?address={SENDER_ADDRESS}',
      symbol: 'BZE',
      z: true,
      dataProviderCode: 'bzedge',
    },
  },
  dogecoin: {
    ...configDefaults,
    ...{
      name: 'Dogecoin',
      logo: 'dogecoin.webp',
      type: 'bitcoin',
      explorer: 'blockbook',
      insight: 'https://dogeblocks.com/',
      insight_addr:
        'https://dogeblocks.com/api/v2/address/{SENDER_ADDRESS}?details=basic',
      insight_tx:
        'https://dogeblocks.com/api/v2/address/{SENDER_ADDRESS}?details=txslight&pageSize=10',
      symbol: 'DOGE',
      dataProviderCode: 'dogecoin',
    },
  },
  tether: {
    ...configDefaults,
    ...{
      name: 'TetherUSD',
      logo: 'tether.webp',
      symbol: 'USDT',
      contractAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
      decimals: 6,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'tether',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  usdcoin: {
    ...configDefaults,
    ...{
      name: 'USD Coin',
      logo: 'usdcoin.webp',
      symbol: 'USDC',
      contractAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      decimals: 6,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'usd-coin',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  enjincoin: {
    ...configDefaults,
    ...{
      name: 'Enjin Coin',
      logo: 'enjincoin.webp',
      symbol: 'ENJ',
      contractAddress: '0xF629cBd94d3791C9250152BD8dfBDF380E2a3B9c',
      decimals: 18,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'enjincoin',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  chainlink: {
    ...configDefaults,
    ...{
      name: 'Chainlink',
      logo: 'chainlink.webp',
      symbol: 'LINK',
      contractAddress: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
      decimals: 18,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'chainlink',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  golem: {
    ...configDefaults,
    ...{
      name: 'Golem',
      logo: 'golem.webp',
      symbol: 'GNT',
      contractAddress: '0xa74476443119A942dE498590Fe1f2454d7D4aC0d',
      decimals: 18,
      erc20: true,
      type: 'ethereum',
      lib: 'ethersjs',
      explorer: 'etherscan',
      insight: 'https://etherscan.io/',
      dataProviderCode: 'golem',
      addrValidationCheck: new RegExp('^0x[a-fA-F0-9]{40}$'),
    },
  },
  commercium: {
    ...configDefaults,
    ...{
      name: 'Commercium',
      logo: 'commercium.webp',
      insight: 'https://explorer.commercium.net/',
      insight_addr: 'https://explorer.commercium.net/api/addr/{SENDER_ADDRESS}',
      insight_tx:
        'https://explorer.commercium.net/api/txs/?address={SENDER_ADDRESS}',
      symbol: 'CMM',
      z: true,
      dataProviderCode: 'commercium',
    },
  },
};
